"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.String = exports.Int = exports.Float = exports.Decimal = exports.DateTime = exports.Boolean = exports.BigInt = void 0;
Object.defineProperty(exports, "enum", {
  enumerable: true,
  get: function () {
    return _enumFilter.enumFilters;
  }
});
var _core = require("@keystone-6/core");
var _enumFilter = require("../enum-filter");
// Do not manually modify this file, it is automatically generated by the package at /prisma-utils in this repo.
// Update the script if you need this file to be different

const StringNullableFilter = _core.graphql.inputObject({
  name: 'CustomStringNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.String
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    contains: _core.graphql.arg({
      type: _core.graphql.String
    }),
    startsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    endsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    // can be null
    not: _core.graphql.arg({
      type: NestedStringNullableFilter
    })
  })
});
const NestedStringNullableFilter = _core.graphql.inputObject({
  name: 'CustomNestedStringNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.String
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    contains: _core.graphql.arg({
      type: _core.graphql.String
    }),
    startsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    endsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    // can be null
    not: _core.graphql.arg({
      type: NestedStringNullableFilter
    })
  })
});
const StringFilter = _core.graphql.inputObject({
  name: 'CustomStringFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.String
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    contains: _core.graphql.arg({
      type: _core.graphql.String
    }),
    startsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    endsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    not: _core.graphql.arg({
      type: NestedStringFilter
    })
  })
});
const NestedStringFilter = _core.graphql.inputObject({
  name: 'CustomNestedStringFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.String
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    contains: _core.graphql.arg({
      type: _core.graphql.String
    }),
    startsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    endsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    not: _core.graphql.arg({
      type: NestedStringFilter
    })
  })
});
const BoolNullableFilter = _core.graphql.inputObject({
  name: 'CustomBooleanNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.Boolean
    }),
    // can be null
    not: _core.graphql.arg({
      type: BoolNullableFilter
    })
  })
});
const BoolFilter = _core.graphql.inputObject({
  name: 'CustomBooleanFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.Boolean
    }),
    not: _core.graphql.arg({
      type: BoolFilter
    })
  })
});
const IntNullableFilter = _core.graphql.inputObject({
  name: 'CustomIntNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Int))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Int))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    // can be null
    not: _core.graphql.arg({
      type: IntNullableFilter
    })
  })
});
const IntFilter = _core.graphql.inputObject({
  name: 'CustomIntFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Int))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Int))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    not: _core.graphql.arg({
      type: IntFilter
    })
  })
});
const FloatNullableFilter = _core.graphql.inputObject({
  name: 'CustomFloatNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Float))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Float))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    // can be null
    not: _core.graphql.arg({
      type: FloatNullableFilter
    })
  })
});
const FloatFilter = _core.graphql.inputObject({
  name: 'CustomFloatFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Float))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Float))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    not: _core.graphql.arg({
      type: FloatFilter
    })
  })
});
const DateTimeNullableFilter = _core.graphql.inputObject({
  name: 'CustomDateTimeNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.DateTime))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.DateTime))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    // can be null
    not: _core.graphql.arg({
      type: DateTimeNullableFilter
    })
  })
});
const DateTimeFilter = _core.graphql.inputObject({
  name: 'CustomDateTimeFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.DateTime))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.DateTime))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    not: _core.graphql.arg({
      type: DateTimeFilter
    })
  })
});
const DecimalNullableFilter = _core.graphql.inputObject({
  name: 'CustomDecimalNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Decimal))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Decimal))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    // can be null
    not: _core.graphql.arg({
      type: DecimalNullableFilter
    })
  })
});
const DecimalFilter = _core.graphql.inputObject({
  name: 'CustomDecimalFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Decimal))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Decimal))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    not: _core.graphql.arg({
      type: DecimalFilter
    })
  })
});
const BigIntNullableFilter = _core.graphql.inputObject({
  name: 'CustomBigIntNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.BigInt))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.BigInt))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    // can be null
    not: _core.graphql.arg({
      type: BigIntNullableFilter
    })
  })
});
const BigIntFilter = _core.graphql.inputObject({
  name: 'CustomBigIntFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.BigInt))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.BigInt))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    not: _core.graphql.arg({
      type: BigIntFilter
    })
  })
});
const String = exports.String = {
  optional: StringNullableFilter,
  required: StringFilter
};
const Boolean = exports.Boolean = {
  optional: BoolNullableFilter,
  required: BoolFilter
};
const Int = exports.Int = {
  optional: IntNullableFilter,
  required: IntFilter
};
const Float = exports.Float = {
  optional: FloatNullableFilter,
  required: FloatFilter
};
const DateTime = exports.DateTime = {
  optional: DateTimeNullableFilter,
  required: DateTimeFilter
};
const Decimal = exports.Decimal = {
  optional: DecimalNullableFilter,
  required: DecimalFilter
};
const BigInt = exports.BigInt = {
  optional: BigIntNullableFilter,
  required: BigIntFilter
};