"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.String = exports.Int = exports.Float = exports.Decimal = exports.DateTime = exports.Boolean = exports.BigInt = void 0;
Object.defineProperty(exports, "enum", {
  enumerable: true,
  get: function () {
    return _enumFilter.enumFilters;
  }
});
var _core = require("@keystone-6/core");
var _types = require("@keystone-6/core/types");
var _enumFilter = require("../enum-filter");
// Do not manually modify this file, it is automatically generated by the package at /prisma-utils in this repo.
// Update the script if you need this file to be different

const StringNullableFilter = _core.graphql.inputObject({
  name: 'CustomStringNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.String
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    contains: _core.graphql.arg({
      type: _core.graphql.String
    }),
    startsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    endsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    mode: _core.graphql.arg({
      type: _types.QueryMode
    }),
    // can be null
    not: _core.graphql.arg({
      type: NestedStringNullableFilter
    })
  })
});
const NestedStringNullableFilter = _core.graphql.inputObject({
  name: 'CustomNestedStringNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.String
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    contains: _core.graphql.arg({
      type: _core.graphql.String
    }),
    startsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    endsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    // can be null
    not: _core.graphql.arg({
      type: NestedStringNullableFilter
    })
  })
});
const StringFilter = _core.graphql.inputObject({
  name: 'CustomStringFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.String
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    contains: _core.graphql.arg({
      type: _core.graphql.String
    }),
    startsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    endsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    mode: _core.graphql.arg({
      type: _types.QueryMode
    }),
    not: _core.graphql.arg({
      type: NestedStringFilter
    })
  })
});
const NestedStringFilter = _core.graphql.inputObject({
  name: 'CustomNestedStringFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.String
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.String
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.String
    }),
    contains: _core.graphql.arg({
      type: _core.graphql.String
    }),
    startsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    endsWith: _core.graphql.arg({
      type: _core.graphql.String
    }),
    not: _core.graphql.arg({
      type: NestedStringFilter
    })
  })
});
const StringNullableListFilter = _core.graphql.inputObject({
  name: 'CustomStringNullableListFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    // can be null
    has: _core.graphql.arg({
      type: _core.graphql.String
    }),
    hasEvery: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    hasSome: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.String))
    }),
    isEmpty: _core.graphql.arg({
      type: _core.graphql.Boolean
    })
  })
});
const BoolNullableFilter = _core.graphql.inputObject({
  name: 'CustomBooleanNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.Boolean
    }),
    // can be null
    not: _core.graphql.arg({
      type: BoolNullableFilter
    })
  })
});
const BoolFilter = _core.graphql.inputObject({
  name: 'CustomBooleanFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.Boolean
    }),
    not: _core.graphql.arg({
      type: BoolFilter
    })
  })
});
const BoolNullableListFilter = _core.graphql.inputObject({
  name: 'CustomBooleanNullableListFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Boolean))
    }),
    // can be null
    has: _core.graphql.arg({
      type: _core.graphql.Boolean
    }),
    hasEvery: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Boolean))
    }),
    hasSome: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Boolean))
    }),
    isEmpty: _core.graphql.arg({
      type: _core.graphql.Boolean
    })
  })
});
const IntNullableFilter = _core.graphql.inputObject({
  name: 'CustomIntNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Int))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Int))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    // can be null
    not: _core.graphql.arg({
      type: IntNullableFilter
    })
  })
});
const IntFilter = _core.graphql.inputObject({
  name: 'CustomIntFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Int))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Int))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    not: _core.graphql.arg({
      type: IntFilter
    })
  })
});
const IntNullableListFilter = _core.graphql.inputObject({
  name: 'CustomIntNullableListFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Int))
    }),
    // can be null
    has: _core.graphql.arg({
      type: _core.graphql.Int
    }),
    hasEvery: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Int))
    }),
    hasSome: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Int))
    }),
    isEmpty: _core.graphql.arg({
      type: _core.graphql.Boolean
    })
  })
});
const FloatNullableFilter = _core.graphql.inputObject({
  name: 'CustomFloatNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Float))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Float))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    // can be null
    not: _core.graphql.arg({
      type: FloatNullableFilter
    })
  })
});
const FloatFilter = _core.graphql.inputObject({
  name: 'CustomFloatFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Float))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Float))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    not: _core.graphql.arg({
      type: FloatFilter
    })
  })
});
const FloatNullableListFilter = _core.graphql.inputObject({
  name: 'CustomFloatNullableListFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Float))
    }),
    // can be null
    has: _core.graphql.arg({
      type: _core.graphql.Float
    }),
    hasEvery: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Float))
    }),
    hasSome: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Float))
    }),
    isEmpty: _core.graphql.arg({
      type: _core.graphql.Boolean
    })
  })
});
const DateTimeNullableFilter = _core.graphql.inputObject({
  name: 'CustomDateTimeNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.DateTime))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.DateTime))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    // can be null
    not: _core.graphql.arg({
      type: DateTimeNullableFilter
    })
  })
});
const DateTimeFilter = _core.graphql.inputObject({
  name: 'CustomDateTimeFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.DateTime))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.DateTime))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    not: _core.graphql.arg({
      type: DateTimeFilter
    })
  })
});
const DateTimeNullableListFilter = _core.graphql.inputObject({
  name: 'CustomDateTimeNullableListFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.DateTime))
    }),
    // can be null
    has: _core.graphql.arg({
      type: _core.graphql.DateTime
    }),
    hasEvery: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.DateTime))
    }),
    hasSome: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.DateTime))
    }),
    isEmpty: _core.graphql.arg({
      type: _core.graphql.Boolean
    })
  })
});
const DecimalNullableFilter = _core.graphql.inputObject({
  name: 'CustomDecimalNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Decimal))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Decimal))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    // can be null
    not: _core.graphql.arg({
      type: DecimalNullableFilter
    })
  })
});
const DecimalFilter = _core.graphql.inputObject({
  name: 'CustomDecimalFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Decimal))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Decimal))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    not: _core.graphql.arg({
      type: DecimalFilter
    })
  })
});
const DecimalNullableListFilter = _core.graphql.inputObject({
  name: 'CustomDecimalNullableListFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Decimal))
    }),
    // can be null
    has: _core.graphql.arg({
      type: _core.graphql.Decimal
    }),
    hasEvery: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Decimal))
    }),
    hasSome: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.Decimal))
    }),
    isEmpty: _core.graphql.arg({
      type: _core.graphql.Boolean
    })
  })
});
const BigIntNullableFilter = _core.graphql.inputObject({
  name: 'CustomBigIntNullableFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    // can be null
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.BigInt))
    }),
    // can be null
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.BigInt))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    // can be null
    not: _core.graphql.arg({
      type: BigIntNullableFilter
    })
  })
});
const BigIntFilter = _core.graphql.inputObject({
  name: 'CustomBigIntFilter',
  fields: () => ({
    equals: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    in: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.BigInt))
    }),
    notIn: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.BigInt))
    }),
    lt: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    lte: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    gt: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    gte: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    not: _core.graphql.arg({
      type: BigIntFilter
    })
  })
});
const BigIntNullableListFilter = _core.graphql.inputObject({
  name: 'CustomBigIntNullableListFilter',
  fields: () => ({
    // can be null
    equals: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.BigInt))
    }),
    // can be null
    has: _core.graphql.arg({
      type: _core.graphql.BigInt
    }),
    hasEvery: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.BigInt))
    }),
    hasSome: _core.graphql.arg({
      type: _core.graphql.list(_core.graphql.nonNull(_core.graphql.BigInt))
    }),
    isEmpty: _core.graphql.arg({
      type: _core.graphql.Boolean
    })
  })
});
const String = exports.String = {
  optional: StringNullableFilter,
  required: StringFilter,
  many: StringNullableListFilter
};
const Boolean = exports.Boolean = {
  optional: BoolNullableFilter,
  required: BoolFilter,
  many: BoolNullableListFilter
};
const Int = exports.Int = {
  optional: IntNullableFilter,
  required: IntFilter,
  many: IntNullableListFilter
};
const Float = exports.Float = {
  optional: FloatNullableFilter,
  required: FloatFilter,
  many: FloatNullableListFilter
};
const DateTime = exports.DateTime = {
  optional: DateTimeNullableFilter,
  required: DateTimeFilter,
  many: DateTimeNullableListFilter
};
const Decimal = exports.Decimal = {
  optional: DecimalNullableFilter,
  required: DecimalFilter,
  many: DecimalNullableListFilter
};
const BigInt = exports.BigInt = {
  optional: BigIntNullableFilter,
  required: BigIntFilter,
  many: BigIntNullableListFilter
};